;; Copyright (c) 2016 xmms2-guile workers, All rights reserved.
;;
;; Terms for redistribution and use can be found in LICENCE.

(define-module (xmms2 constants collection)
  #:use-module (xmms2 constants)
  #:use-module (xmms2 enumeration))

(define-enum (<> xref-collection-cmds)
  (CMD-COLLECTION-GET FIRST-CMD-ID)
  CMD-COLLECTION-LIST
  CMD-COLLECTION-SAVE
  CMD-COLLECTION-REMOVE
  CMD-COLLECTION-FIND
  CMD-COLLECTION-RENAME
  CMD-QUERY
  CMD-QUERY-INFOS
  CMD-IDLIST-FROM-PLS)

(define-enum (<> xref-collection-signals)
  COLLECTION-CHANGED-ADD
  COLLECTION-CHANGED-UPDATE
  COLLECTION-CHANGED-RENAME
  COLLECTION-CHANGED-REMOVE)

(define-enum (<> xref-collection-types)
  COLLECTION-TYPE-REFERENCE
  COLLECTION-TYPE-UNIVERSE
  COLLECTION-TYPE-UNION
  COLLECTION-TYPE-INTERSECTION
  COLLECTION-TYPE-COMPLEMENT
  COLLECTION-TYPE-HAS
  COLLECTION-TYPE-MATCH
  COLLECTION-TYPE-TOKEN
  COLLECTION-TYPE-EQUAL
  COLLECTION-TYPE-NOT-EQUAL
  COLLECTION-TYPE-SMALLER
  COLLECTION-TYPE-SMALLER-OR-EQUAL
  COLLECTION-TYPE-GREATER
  COLLECTION-TYPE-GREATER-OR-EQUAl
  COLLECTION-TYPE-ORDER
  COLLECTION-TYPE-LIMIT
  COLLECTION-TYPE-MEDIASET
  COLLECTION-TYPE-IDLIST)
