__compiler_knows_option(Wall)
__compiler_knows_option(Wextra)
__compiler_knows_option(Wunused)
__compiler_knows_option(Wold-style-definition)
__compiler_knows_option(Wmissing-prototypes)
__compiler_knows_option(Wmissing-declarations)
__compiler_knows_option(Wmissing-field-initializers)
__compiler_knows_option(Wdeclaration-after-statement)
__compiler_knows_option(Wno-multichar)
__compiler_knows_option(Wformat)
__compiler_knows_option(Wformat-nonliteral)
__compiler_knows_option(Wformat-security)
__compiler_knows_option(Wformat-y2k)
__compiler_knows_option(Wmissing-braces)

if (ENABLE_STRICT)
    __compiler_knows_option(Werror)
endif (ENABLE_STRICT)

if (ENABLE_STACK_PROTECTOR)
    __compiler_knows_option(fstack-protector)
endif (ENABLE_STACK_PROTECTOR)

__compiler_knows_feature(cold)
__compiler_knows_feature(deprecated)
__compiler_knows_feature(expect)
__compiler_knows_feature(hot)
__compiler_knows_feature(noreturn)
__compiler_knows_feature(printf_fmt)
__compiler_knows_feature(unused)
__compiler_knows_feature(warn_unused_result)
