#!/bin/sh

is_opt () {
    case "$1" in
    -*) return 0 ;;
    esac
    return 1
}

case "$1" in
module) mode=module ;;
combine) mode=combine ;;
*) printf 'usage: docc MODE [OPTION(s)...] INPUT\n'
   exit 1
   ;;
esac

shift

guessmodule=0
while is_opt "$1"; do
    case "$1" in
    -o) output="$2"
        shift 2
        ;;
    -g) guessmodule=1
        shift
        ;;
    *) printf 'Unknown option: ‘%s’\n' "$1"
       exit 1
       ;;
    esac
done

has_prefix () {
    case "$1" in
    [./]* ) return 0 ;;
    esac
    return 1
}

input="$1"
shift
if test "$guessmodule" = 1; then
    while has_prefix "$input"; do
        input=${input#?}
    done
    input=${input#scheme/}
    input=${input%.scm}
    input="($(printf '%s' ${input} | tr / ' '))"
fi

maybe_output () {
    if test "x$output" = x; then
        "$@"
    else
        "$@" > "$output" || mv "$output" "${output}.failure"
    fi
}

case "$mode" in
module)
    maybe_output "$TOPDIR/tools/guile-in-here" "$TOPDIR/tools/module-to-markdown.scm" "$input"
    ;;

combine)
    maybe_output "$TOPDIR/tools/guile-in-here" "$TOPDIR/tools/combine-into-markdown.scm" "$input"
    ;;

*)
    printf 'BUG: This should not happen! Please report!\n'
    exit 2
    ;;
esac
